import * as T from './three.module.js';
import {body,drive,integrate,collide,forward,STEP} from './physics.mjs';
import {createWorld,createCar,animateCar,dent,repair} from './visuals.js';
import {createPeople} from './people.js';
const $=id=>document.getElementById(id),keys={},scene=new T.Scene();
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('overlay').innerHTML='<div class="intro"><h2>WebGL is unavailable.</h2><p>Enable hardware acceleration in your browser, then reload.</p></div>';throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('world').appendChild(renderer.domElement);
const camera=new T.PerspectiveCamera(60,innerWidth/innerHeight,.15,1800),world=createWorld(scene,renderer);const obstacles=world.blocks.map(b=>body(b.x,b.z,0,0,b.w,b.d));obstacles.push(body(0,330,0,0,340,2),body(0,-330,0,0,340,2),body(330,0,0,0,2,340),body(-330,0,0,0,2,340));
let player=createCar('#9fae86');scene.add(player);let car=body(4,18);let nitro=100,score=0,gates=0,playing=false,started=false,chasing=false,camMode=0,notice=0,chaseTime=0,accumulator=0,shake=0,simTime=0,hitCooldown=0;player.position.set(car.x,0,car.z);
for(const x of [-.68,.68]){const lamp=new T.SpotLight('#fff3d7',24,42,.28,.65,1.4);lamp.position.set(x,.8,2.2);lamp.target.position.set(x,.3,26);player.add(lamp,lamp.target);}
const actors=[];for(let i=0;i<20;i++){const axis=i%2,road=world.roads[(i*5)%9],dir=i%3?1:-1,pos=((i*97)%590)-295;const b=body(axis?pos:road+dir*4,axis?road+dir*4:pos,axis?dir*Math.PI/2:dir>0?0:Math.PI);const mesh=createCar(['#676f7e','#bbaca2','#934b44','#c6c9ca','#374952'][i%5]);scene.add(mesh);actors.push({b,mesh,axis,road,dir,s:10+i%7,recover:0,police:false,active:true})}
for(let i=0;i<2;i++){const mesh=createCar('#d0d8de',true);mesh.visible=false;scene.add(mesh);actors.push({b:body(),mesh,police:true,active:false,recover:0})}
// Parked vehicles can be entered; the chosen car becomes the controlled rigid body.
for(const [x,z,yaw] of [[8,43,0],[-8,25,Math.PI],[64,52,0],[80,-20,Math.PI],[-63,-18,0]]){const mesh=createCar('#69788a');scene.add(mesh);actors.push({b:body(x,z,yaw),mesh,parked:true,active:true,recover:0,police:false})}
function getVehicle(){return {b:car,mesh:player,active:true,parked:true}}
function takeVehicle(v){if(v.b===car)return;actors.push({b:car,mesh:player,active:true,parked:true,recover:0,police:false});const i=actors.findIndex(a=>a.b===v.b);if(i>=0)actors.splice(i,1);car=v.b;player=v.mesh;camMode=0;}
const people=createPeople(scene,{obstacles,getVehicles:()=>[getVehicle(),...actors],getVehicle,takeVehicle,toast});
let footYaw=0,footPitch=.08,dragging=false,pointerX=0,pointerY=0,fireHeld=false;
const raycaster=new T.Raycaster(),rayDirection=new T.Vector3(),rayOrigin=new T.Vector3();
const tracer=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineBasicMaterial({color:'#ffe1a0',transparent:true,opacity:.85}));tracer.visible=false;tracer.frustumCulled=false;scene.add(tracer);let tracerLife=0;
function shot(){if(!playing||!people.shoot())return;const h=people.state;camera.getWorldDirection(rayDirection);rayOrigin.set(h.x+Math.sin(footYaw)*.5,1.4+h.jumpY,h.z+Math.cos(footYaw)*.5);raycaster.set(rayOrigin,rayDirection);raycaster.camera=camera;raycaster.far=100;scene.updateMatrixWorld(true);const candidates=[...scene.children].filter(o=>!o.isSprite&&!o.isPoints&&o!==people.hero&&o!==tracer&&o!==marker&&o!==world.sky);const hits=raycaster.intersectObjects(candidates,true);const hit=hits.find(h=>h.distance>.15&&!h.object.isPoints&&!h.object.isSprite&&h.object!==beam&&h.object!==ring);const end=hit?hit.point:rayOrigin.clone().addScaledVector(rayDirection,100);tracer.geometry.attributes.position.setXYZ(0,rayOrigin.x,rayOrigin.y,rayOrigin.z);tracer.geometry.attributes.position.setXYZ(1,end.x,end.y,end.z);tracer.geometry.attributes.position.needsUpdate=true;tracer.visible=true;tracerLife=.055;people.scare(end.x,end.z,18);if(hit){for(let i=0;i<5;i++){const p=sparks[particleCursor++%sparks.length];Object.assign(p,{life:.22,x:end.x,y:end.y,z:end.z,vx:(Math.random()-.5)*2,vy:Math.random()*2,vz:(Math.random()-.5)*2})}}crashSound(3);}
function wheel(){if(!playing||people.state.mode!=='foot')return;const el=$('weapon-wheel');el.hidden=!el.hidden;fireHeld=false;}
renderer.domElement.addEventListener('pointerdown',e=>{if(!playing||people.state.mode!=='foot')return;dragging=true;pointerX=e.clientX;pointerY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);if(e.button===0&&e.pointerType!=='touch'){fireHeld=true;shot()}});
renderer.domElement.addEventListener('pointermove',e=>{if(!dragging||people.state.mode!=='foot')return;footYaw-=(e.clientX-pointerX)*.005;footPitch=T.MathUtils.clamp(footPitch+(e.clientY-pointerY)*.004,-.4,.65);pointerX=e.clientX;pointerY=e.clientY;});
renderer.domElement.addEventListener('pointerup',()=>{dragging=false;fireHeld=false});renderer.domElement.addEventListener('pointercancel',()=>{dragging=false;fireHeld=false});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>people.equip(Number(b.dataset.weapon)));
$('weapon-toggle').onclick=wheel;$('enter-mobile').onclick=()=>{if(playing)people.interact()};$('fire-mobile').onpointerdown=e=>{e.preventDefault();fireHeld=true;shot()};$('fire-mobile').onpointerup=$('fire-mobile').onpointercancel=()=>fireHeld=false;
const targets=[[4,144],[144,148],[220,4],[76,-144],[-140,-212],[-212,4],[-68,220],[292,220]];let target=0;const marker=new T.Group();const ring=new T.Mesh(new T.TorusGeometry(4.8,.1,8,48),new T.MeshBasicMaterial({color:'#d2fca1'}));ring.rotation.x=Math.PI/2;marker.add(ring);const beam=new T.Mesh(new T.CylinderGeometry(4,4,23,24,1,true),new T.MeshBasicMaterial({color:'#cffb8c',transparent:true,opacity:.06,side:T.DoubleSide,depthWrite:false}));beam.position.y=11.5;marker.add(beam);scene.add(marker);function moveTarget(){marker.position.set(...[targets[target][0],.3,targets[target][1]])}moveTarget();
const sparkGeo=new T.BufferGeometry(),sparkPos=new Float32Array(240*3),sparks=Array.from({length:240},()=>({life:0,x:0,y:-20,z:0,vx:0,vy:0,vz:0}));sparkGeo.setAttribute('position',new T.BufferAttribute(sparkPos,3));const sparkMesh=new T.Points(sparkGeo,new T.PointsMaterial({color:'#ffcb73',size:.1,transparent:true,opacity:.9,depthWrite:false}));sparkMesh.frustumCulled=false;scene.add(sparkMesh);let particleCursor=0;
const smokeCanvas=document.createElement('canvas');smokeCanvas.width=smokeCanvas.height=64;const sc=smokeCanvas.getContext('2d'),sg=sc.createRadialGradient(32,32,0,32,32,32);sg.addColorStop(0,'rgba(90,95,100,.6)');sg.addColorStop(1,'rgba(90,95,100,0)');sc.fillStyle=sg;sc.fillRect(0,0,64,64);const smokeMap=new T.CanvasTexture(smokeCanvas);const smoke=Array.from({length:32},()=>{const m=new T.Sprite(new T.SpriteMaterial({map:smokeMap,transparent:true,depthWrite:false,opacity:0}));scene.add(m);return {m,life:0}});let smokeCursor=0;
const skidGeo=new T.PlaneGeometry(.19,.7);skidGeo.rotateX(-Math.PI/2);const skid=new T.InstancedMesh(skidGeo,new T.MeshBasicMaterial({color:'#111315',transparent:true,opacity:.35,depthWrite:false}),500);skid.count=0;skid.frustumCulled=false;scene.add(skid);let skidIndex=0,skidClock=0;const dummy=new T.Object3D();
function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;notice=3}
function impact(hit,mesh,other){if(hit.impact<2)return;dent(mesh,hit.x,hit.z,hit.impact);if(other)dent(other,hit.x,hit.z,hit.impact);for(let i=0;i<Math.min(28,hit.impact*1.5);i++){const p=sparks[particleCursor++%sparks.length];Object.assign(p,{life:.35+Math.random()*.5,x:hit.x,y:.5,z:hit.z,vx:hit.nx*2+(Math.random()-.5)*8,vy:Math.random()*5,vz:hit.nz*2+(Math.random()-.5)*8})}if(mesh===player||other===player){shake=Math.min(.65,hit.impact*.025);if(hitCooldown<=0){toast(`${Math.round(hit.impact*3.6)} KM/H IMPACT • R TO REPAIR`);crashSound(hit.impact);hitCooldown=.7}}}
function placeCops(){actors.filter(a=>a.police).forEach((a,i)=>{Object.assign(a.b,body(car.x+3+i*4,car.z-45-i*15));a.active=chasing;a.mesh.visible=chasing;})}
function chase(){chasing=!chasing;chaseTime=0;placeCops();$('chase').textContent=chasing?'× END POLICE CHASE':'＋ START POLICE CHASE';$('heat').textContent=chasing?'★ ★ ☆   PURSUIT ACTIVE':'○ ○ ○   NO HEAT';$('heat').style.color=chasing?'#ff8097':'#919ab5';$('mode').textContent=chasing?'PURSUIT':'FREE ROAM';toast(chasing?'STAY MOVING. LOSE THE TAIL.':'BACK TO FREE ROAM')}
function reset(){if(people.state.mode!=='driving'){people.reload();return}Object.assign(car,body(4,18));repair(player);nitro=100;shake=0;if(chasing)placeCops();toast('CAR REPAIRED • BACK ON THE ROAD')}
$('chase').onclick=chase;function clearKeys(){for(const k in keys)keys[k]=false;fireHeld=false;dragging=false}
function togglePause(){if(!started)return;playing=!playing;accumulator=0;$('overlay').style.display=playing?'none':'flex';$('start').innerHTML='RESUME DRIVE <span>↗</span>';$('pause').textContent=playing?'Ⅱ PAUSE':'▶ RESUME';clearKeys()}
$('pause').onclick=togglePause;$('start').onclick=()=>{started=playing=true;$('overlay').style.display='none';$('pause').textContent='Ⅱ PAUSE';toast('WASD WALK • F ENTER CAR • 1–3 WEAPONS')};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(e.repeat)return;if(k==='c'&&people.state.mode==='driving')camMode=(camMode+1)%3;if(k==='r'&&playing)reset();if(k==='f'&&playing){footYaw=car.yaw;people.interact()}if(k==='q')wheel();if(['1','2','3'].includes(k)&&playing)people.equip(Number(k)-1);if(k==='escape'||k==='p')togglePause()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>{clearKeys();if(playing)togglePause()});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false});
let audio,osc,gain,sound=false;$('sound').onclick=()=>{sound=!sound;if(!audio){audio=new AudioContext();osc=audio.createOscillator();gain=audio.createGain();const filter=audio.createBiquadFilter();filter.frequency.value=380;osc.type='sawtooth';osc.connect(filter);filter.connect(gain);gain.connect(audio.destination);osc.start()}audio.resume();$('sound').textContent=sound?'SOUND ON':'SOUND OFF'};
function crashSound(strength){if(!audio||!sound)return;const buffer=audio.createBuffer(1,audio.sampleRate*.2,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,3);const source=audio.createBufferSource(),g=audio.createGain();source.buffer=buffer;g.gain.value=Math.min(.4,strength*.01);source.connect(g);g.connect(audio.destination);source.start();source.onended=()=>{source.disconnect();g.disconnect()}}
function input(){if(people.state.mode!=='driving')return {gas:false,brake:true,steer:0,drift:false,boost:false};return {gas:keys.w||keys.arrowup,brake:keys.s||keys.arrowdown,steer:(keys.a||keys.arrowleft?1:0)-(keys.d||keys.arrowright?1:0),drift:keys[' '],boost:keys.shift&&nitro>0&&(keys.w||keys.arrowup)}}
function step(dt){simTime+=dt;hitCooldown-=dt;const control=input();if(people.state.mode==='driving')drive(car,control,dt);else{car.vx*=Math.exp(-5*dt);car.vz*=Math.exp(-5*dt);car.omega*=Math.exp(-5*dt)}integrate(car,dt);people.step(dt,keys,footYaw);nitro=T.MathUtils.clamp(nitro+(control.boost?-25:8)*dt,0,100);
for(const a of actors){if(!a.active)continue;if(a.held){a.b.vx=a.b.vz=a.b.omega=0;continue}if(a.parked){a.b.vx*=Math.exp(-3*dt);a.b.vz*=Math.exp(-3*dt);a.b.omega*=Math.exp(-3*dt);integrate(a.b,dt);continue}if(a.recover>0){a.recover-=dt;a.b.vx*=Math.exp(-.5*dt);a.b.vz*=Math.exp(-.5*dt);a.b.omega*=Math.exp(-1.6*dt)}else{let targetYaw,velocity=a.s||23;if(a.police){const target=people.state.mode==='driving'?car:people.state;targetYaw=Math.atan2(target.x-a.b.x,target.z-a.b.z)}else{targetYaw=a.axis?a.dir*Math.PI/2:a.dir>0?0:Math.PI;const laneError=a.road+a.dir*4-(a.axis?a.b.z:a.b.x);targetYaw+=(a.axis?-1:1)*a.dir*T.MathUtils.clamp(laneError*.03,-.45,.45)}let diff=Math.atan2(Math.sin(targetYaw-a.b.yaw),Math.cos(targetYaw-a.b.yaw));a.b.omega=T.MathUtils.lerp(a.b.omega,diff*1.7,dt*3);const f=forward(a.b);a.b.vx=T.MathUtils.lerp(a.b.vx,f.x*velocity,dt*.8);a.b.vz=T.MathUtils.lerp(a.b.vz,f.z*velocity,dt*.8)}integrate(a.b,dt);if(!a.police&&(Math.abs(a.b.x)>323||Math.abs(a.b.z)>323)){if(a.axis){a.b.x=-a.dir*315;a.b.z=a.road+a.dir*4}else{a.b.z=-a.dir*315;a.b.x=a.road+a.dir*4}a.b.yaw=a.axis?a.dir*Math.PI/2:a.dir>0?0:Math.PI;}}
const dynamic=[{b:car,mesh:player,active:true},...actors.filter(a=>a.active)];for(const a of dynamic)for(const wall of obstacles){const hit=collide(a.b,wall);if(hit){impact(hit,a.mesh);if(a!==dynamic[0])a.recover=Math.max(a.recover||0,.4)}}for(let i=0;i<dynamic.length;i++)for(let j=i+1;j<dynamic.length;j++){const a=dynamic[i],b=dynamic[j],hit=collide(a.b,b.b);if(hit){impact(hit,a.mesh,b.mesh);a.recover=2;b.recover=2}}
const speed=Math.hypot(car.vx,car.vz);score+=speed*dt*(control.drift&&control.steer?2:.2);if(people.state.mode==='driving'&&Math.hypot(car.x-marker.position.x,car.z-marker.position.z)<6){gates++;score+=500;target=(target+1)%targets.length;moveTarget();toast('+500 • CHECKPOINT CLEARED')}
if(chasing){chaseTime+=dt;const far=actors.filter(a=>a.police).every(a=>Math.hypot((people.state.mode==='driving'?car.x:people.state.x)-a.b.x,(people.state.mode==='driving'?car.z:people.state.z)-a.b.z)>95);if(far&&chaseTime>12){chase();score+=1500;toast('+1500 • YOU LOST THE COPS')}}
if((control.drift||Math.abs(car.omega)>1)&&speed>8){skidClock+=dt;if(skidClock>.04){skidClock=0;for(const x of [-.95,.95]){dummy.position.set(car.x+Math.cos(car.yaw)*x-Math.sin(car.yaw)*1.5,.025,car.z-Math.sin(car.yaw)*x-Math.cos(car.yaw)*1.5);dummy.rotation.set(0,car.yaw,0);dummy.updateMatrix();skid.setMatrixAt(skidIndex++%500,dummy.matrix);skid.count=Math.min(500,skidIndex);skid.instanceMatrix.needsUpdate=true}}}}
const map=$('map').getContext('2d');function drawMap(){map.fillStyle='#18232e';map.fillRect(0,0,220,180);const scale=.265,X=x=>110+x*scale,Z=z=>90-z*scale;map.strokeStyle='#515863';map.lineWidth=4;for(const p of world.roads){map.beginPath();map.moveTo(X(p),Z(-330));map.lineTo(X(p),Z(330));map.stroke();map.beginPath();map.moveTo(X(-330),Z(p));map.lineTo(X(330),Z(p));map.stroke()}map.fillStyle='#bce787';map.beginPath();map.arc(X(marker.position.x),Z(marker.position.z),4,0,7);map.fill();if(chasing){map.fillStyle='#ff6280';actors.filter(a=>a.police).forEach(a=>map.fillRect(X(a.b.x)-2,Z(a.b.z)-2,4,4))}map.save();const focus=people.state.mode==='driving'?car:people.state;map.fillStyle='#b19c8a';for(const p of people.pedestrians)map.fillRect(X(p.x),Z(p.z),1.5,1.5);map.translate(X(focus.x),Z(focus.z));map.rotate(focus.yaw);map.fillStyle='#fff';map.beginPath();map.moveTo(0,-6);map.lineTo(4,5);map.lineTo(0,3);map.lineTo(-4,5);map.closePath();map.fill();map.restore()}
let last=performance.now(),smokeClock=0;const desired=new T.Vector3(),look=new T.Vector3();camera.position.set(13,5.2,8);
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.06);last=now;if(playing){accumulator+=dt;while(accumulator>=STEP){step(STEP);accumulator-=STEP}}
const speed=Math.hypot(car.vx,car.vz),f=forward(car),signedSpeed=car.vx*f.x+car.vz*f.z;animateCar(player,car,signedSpeed,input().steer,playing?dt:0,simTime);for(const a of actors)if(a.active)animateCar(a.mesh,a.b,a.b.vx*Math.sin(a.b.yaw)+a.b.vz*Math.cos(a.b.yaw),0,playing?dt:0,simTime);player.visible=people.state.mode!=='driving'||camMode!==2||!started;people.updateHUD();if(playing&&fireHeld&&people.state.weapon===2)shot();tracerLife-=playing?dt:0;tracer.visible=tracerLife>0;
if(playing){$('speed').textContent=String(Math.round(speed*3.6)).padStart(3,'0');$('score').textContent=String(Math.floor(score)).padStart(4,'0');$('gates').textContent=gates;$('nitro').style.width=nitro+'%';$('damage').textContent=`BODY ${Math.round(100-player.userData.damage)}%`;
for(let i=0;i<sparks.length;i++){const p=sparks[i];if(p.life>0){p.life-=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.y+=p.vy*dt;p.vy-=10*dt;if(p.y<.04){p.y=.04;p.vy*=-.3}}sparkPos[i*3]=p.x;sparkPos[i*3+1]=p.life>0?p.y:-20;sparkPos[i*3+2]=p.z}sparkGeo.attributes.position.needsUpdate=true;
smokeClock+=dt;if(player.userData.damage>35&&smokeClock>.13){smokeClock=0;const p=smoke[smokeCursor++%smoke.length];p.life=1.8;p.m.position.set(car.x+f.x*1.4,.9,car.z+f.z*1.4)}for(const p of smoke)if(p.life>0){p.life-=dt;p.m.position.y+=dt*.9;p.m.position.x+=dt*.3;const age=1.8-p.life;p.m.scale.setScalar(.4+age*1.5);p.m.material.opacity=Math.max(0,p.life*.35)}
}if(notice>0){notice-=dt;if(notice<=0)$('toast').style.opacity=0}if(gain){gain.gain.setTargetAtTime(sound&&playing&&people.state.mode==='driving'?.023:0,audio.currentTime,.1);osc.frequency.setTargetAtTime(38+speed*2.7,audio.currentTime,.1)}
ring.position.y=.25+Math.sin(now*.002)*.15;
if(started&&people.state.mode!=='driving'){const h=people.state;const f=new T.Vector3(Math.sin(footYaw),0,Math.cos(footYaw));const side=people.state.weapon?.65:0;desired.set(h.x-f.x*5.4+Math.cos(footYaw)*side,2.7+Math.sin(footPitch)*5,h.z-f.z*5.4-Math.sin(footYaw)*side);camera.position.lerp(desired,1-Math.exp(-9*dt));look.set(h.x+f.x*5,1.4-Math.sin(footPitch)*5,h.z+f.z*5);camera.lookAt(look);camera.fov=T.MathUtils.lerp(camera.fov,people.state.speed>4?68:60,dt*4);camera.updateProjectionMatrix();}else if(started){const dist=camMode===1?20:camMode===2?1.1:10;desired.set(car.x-f.x*dist,camMode===1?16:camMode===2?1.45:4.3,car.z-f.z*dist);camera.position.lerp(desired,1-Math.exp(-7*dt));shake*=Math.exp(-6*dt);if(playing){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}look.set(car.x+f.x*13,camMode===2?1.4:1.1,car.z+f.z*13);camera.lookAt(look);camera.fov=T.MathUtils.lerp(camera.fov,60+speed*.14,dt*2);camera.updateProjectionMatrix();}else{camera.position.set(car.x+10+Math.sin(now*.0001)*3,4.7,car.z+9);camera.lookAt(car.x,.75,car.z)}const focus=people.state.mode==='driving'?car:people.state;world.sun.position.set(focus.x-90,140,focus.z-90);world.sun.target.position.set(focus.x,0,focus.z);drawMap();renderer.render(scene,camera)}requestAnimationFrame(frame);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
