import * as T from './three.module.js';
import {ENTRY_DURATION,doorPoint,nearestVehicle,exitPoint,transitionPose,movePerson,clearPosition,loadout,WEAPONS,fireWeapon,reloadWeapon,tickWeapon,localPoint} from './character-state.mjs';
const skinColors=['#b68160','#d4a07d','#8e5f49','#c99576','#664535'];
const sphere=new T.SphereGeometry(1,12,8),limbGeo=new T.CapsuleGeometry(.075,.25,3,8);
function mat(c){return new T.MeshStandardMaterial({color:c,roughness:.85})}
function ellipsoid(parent,m,x,y,z,sx,sy,sz){const o=new T.Mesh(sphere,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;parent.add(o);return o}
function cuboid(parent,m,x,y,z,w,h,d){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o}
export function createPerson({shirt='#59684c',pants='#303c50',skin='#bd8d6c',hero=false}={}){
 const root=new T.Group(),rig=new T.Group();root.add(rig);const jacket=mat(shirt),denim=mat(pants),skinMat=mat(skin),shoe=mat('#222728'),hair=mat('#25201e');
 ellipsoid(rig,jacket,0,1.16,0,.25,.35,.15);ellipsoid(rig,denim,0,.86,0,.2,.14,.14);ellipsoid(rig,skinMat,0,1.53,0,.073,.09,.073);const head=new T.Group();head.position.y=1.7;rig.add(head);ellipsoid(head,skinMat,0,0,0,.13,.17,.125);ellipsoid(head,hair,0,.085,-.025,.137,.11,.122);ellipsoid(head,skinMat,0,-.015,.126,.035,.047,.037);const eyes=[];for(const x of [-.05,.05])eyes.push(ellipsoid(head,shoe,x,.025,.113,.016,.012,.01));
 if(hero){cuboid(rig,mat('#b6baa5'),0,1.21,.15,.018,.4,.018);cuboid(rig,mat('#8b9a77'),.13,1.25,.14,.1,.1,.027);ellipsoid(head,hair,0,-.105,.04,.108,.048,.082)}
 const arms=[],legs=[];for(const side of [-1,1]){const upper=new T.Group();upper.position.set(side*.265,1.35,0);rig.add(upper);ellipsoid(upper,jacket,0,-.14,0,.082,.22,.086);const fore=new T.Group();fore.position.y=-.31;upper.add(fore);ellipsoid(fore,jacket,0,-.1,0,.07,.16,.075);ellipsoid(fore,skinMat,0,-.265,0,.067,.08,.055);arms.push({upper,fore});const thigh=new T.Group();thigh.position.set(side*.108,.83,0);rig.add(thigh);ellipsoid(thigh,denim,0,-.19,0,.095,.23,.105);const knee=new T.Group();knee.position.y=-.36;thigh.add(knee);ellipsoid(knee,denim,0,-.17,0,.075,.21,.08);ellipsoid(knee,shoe,0,-.36,.063,.09,.07,.17);legs.push({thigh,knee})}
 const gun=new T.Group();arms[1].fore.add(gun);gun.position.set(0,-.29,.045);gun.rotation.x=1.53;const gunMat=mat('#293038');cuboid(gun,gunMat,0,0,.1,.075,.09,.25);cuboid(gun,gunMat,0,-.07,.015,.065,.14,.065);const barrel=cuboid(gun,mat('#171b20'),0,.02,.26,.052,.055,.09);const mag=cuboid(gun,gunMat,0,-.11,.1,.06,.22,.075);mag.visible=false;gun.visible=false;root.userData={rig,head,arms,legs,gun,barrel,mag,eyes,cycle:Math.random()*6,time:Math.random()*10};return root;
}
export function posePerson(root,{speed=0,dt=0,crouch=0,reach=0,weapon=0,recoil=0,reloading=false,seated=false}={}){const d=root.userData;d.time+=dt;d.cycle+=dt*speed*3.8;const gait=Math.min(speed/2.8,1),a=Math.sin(d.cycle)*.65*gait;d.rig.position.y=Math.abs(Math.sin(d.cycle))*gait*.035-crouch*.22+Math.sin(d.time*2.4)*.006;d.rig.rotation.x=crouch*.35+(speed>4?.12:0);d.rig.rotation.z=Math.sin(d.time*.8)*.012*(1-gait);d.head.rotation.y=weapon?0:Math.sin(d.time*.7)*.13*(1-gait);for(const eye of d.eyes)eye.scale.y=(d.time%4.7<.12)?.002:.012;for(let i=0;i<2;i++){const s=i?-1:1;d.legs[i].thigh.rotation.x=seated?-1.3:s*a-crouch*.65;d.legs[i].knee.rotation.x=seated?1.4:Math.max(0,-s*a)*.8+crouch;d.arms[i].upper.rotation.x=-s*a*.8-reach*1.4;d.arms[i].upper.rotation.z=(i?-.08:.08)*(1-reach);d.arms[i].fore.rotation.x=-.12-reach*.6}d.gun.visible=weapon>0;d.mag.visible=weapon===2;d.barrel.scale.z=weapon===2?2:1;if(weapon){d.arms[1].upper.rotation.x=-1.25-recoil*.25;d.arms[1].fore.rotation.x=-.28;d.arms[0].upper.rotation.x=weapon===2?-1.1:-.3;d.arms[0].upper.rotation.z=weapon===2?-.5:.08;if(reloading){d.arms[1].upper.rotation.x=-.75;d.arms[1].fore.rotation.x=-.7;d.arms[0].upper.rotation.x=-.8;d.arms[0].upper.rotation.z=-.7;d.arms[0].fore.rotation.x=-.7+Math.sin(d.time*14)*.3;d.gun.rotation.z=Math.sin(d.time*9)*.15}else d.gun.rotation.z=0}}
export function createPeople(scene,{obstacles,getVehicles,getVehicle,takeVehicle,toast}){
 const hero=createPerson({hero:true});scene.add(hero);const driver=createPerson({hero:true});driver.scale.setScalar(.86);driver.position.set(.38,-.22,-.23);driver.visible=false;const state={x:7,z:18,yaw:0,mode:'foot',speed:0,time:0,animation:null,weapon:0,recoil:0,health:100,jumpY:0,jumpVelocity:0,spaceDown:false};hero.position.set(state.x,0,state.z);const inventory=loadout();const pedestrians=[];
 for(let i=0;i<36;i++){const ix=(i%6)-3,iz=Math.floor(i/6)-2,cx=ix*72+36,cz=iz*72+36;const path=[{x:cx-25,z:cz-25},{x:cx+25,z:cz-25},{x:cx+25,z:cz+25},{x:cx-25,z:cz+25}],edge=i%4,start=path[edge],end=path[(edge+1)%4],f=(i*.37)%1;const mesh=createPerson({shirt:['#55677b','#a77c63','#6c7168','#817488','#b5afa2'][i%5],pants:i%3?'#303944':'#5d5550',skin:skinColors[i%5]});scene.add(mesh);pedestrians.push({mesh,x:start.x+(end.x-start.x)*f,z:start.z+(end.z-start.z)*f,yaw:0,path,target:(edge+1)%4,speed:1.1+(i%4)*.12,panic:0,stagger:0,wait:0});mesh.position.set(start.x+(end.x-start.x)*f,0,start.z+(end.z-start.z)*f)}
 function vehicles(){return getVehicles().filter(v=>v.active)}
 function personObstacles(exclude){return [...obstacles,...vehicles().filter(v=>v.b!==exclude).map(v=>v.b)]}
 function interact(){if(state.mode==='entering'||state.mode==='exiting')return;
 if(state.mode==='driving'){const v=getVehicle();if(Math.hypot(v.b.vx,v.b.vz)>2.5){toast('STOP THE CAR BEFORE GETTING OUT');return}const p=exitPoint(v.b,personObstacles(v.b));if(!p){toast('DOOR BLOCKED • MOVE THE CAR');return}state.mode='exiting';state.animation={v,from:p,to:localPoint(v.b,p.side*.38,-.05),side:p.side,t:0};hero.visible=true;return}
 const v=nearestVehicle(state,vehicles());if(!v){toast('WALK TO THE DRIVER’S DOOR OF A STOPPED CAR');return}const p=doorPoint(v.b);if(!clearPosition(p.x,p.z,personObstacles(v.b))){toast('DOOR BLOCKED');return}v.b.vx=v.b.vz=v.b.omega=0;v.held=true;state.jumpY=state.jumpVelocity=0;state.mode='entering';state.animation={v,from:{x:state.x,z:state.z},to:localPoint(v.b,.38,-.05),side:1,t:0};state.weapon=0;}
 function equip(index){if(state.mode!=='foot')return;state.weapon=index;document.getElementById('weapon-wheel').hidden=true;toast(WEAPONS[index].name.toUpperCase()+' EQUIPPED')}
 function reload(){if(state.mode==='foot'&&reloadWeapon(inventory[state.weapon],state.weapon))toast('RELOADING…')}
 function scare(x,z,radius=32){for(const p of pedestrians)if(Math.hypot(p.x-x,p.z-z)<radius){p.panic=4+Math.random()*3;if(Math.hypot(p.x-x,p.z-z)<2)p.stagger=.4}}
 function shoot(){if(state.mode!=='foot')return false;const slot=inventory[state.weapon];if(!fireWeapon(slot,state.weapon)){if(state.weapon&&slot.ammo===0&&slot.reload===0)reload();return false}state.recoil=1;scare(state.x,state.z);return true}
 function step(dt,keys,yaw){state.time+=dt;state.recoil=Math.max(0,state.recoil-dt*6);inventory.forEach((s,i)=>tickWeapon(s,i,dt));
 if(state.animation){const a=state.animation;a.t=Math.min(1,a.t+dt/ENTRY_DURATION);a.v.b.vx=a.v.b.vz=a.v.b.omega=0;const pose=transitionPose(a.t,a.from,a.to,state.mode==='entering');state.x=pose.x;state.z=pose.z;state.yaw=a.v.b.yaw;hero.position.set(pose.x,pose.y,pose.z);hero.rotation.y=state.yaw;hero.visible=pose.visible;posePerson(hero,{dt,speed:a.t<.3?1.8:0,crouch:pose.crouch,reach:pose.door});const door=a.v.mesh.userData.doors?.[a.side===1?0:1];if(door)door.rotation.y=-a.side*pose.door*1.15;
 if(a.t===1){if(door)door.rotation.y=0;a.v.held=false;if(state.mode==='entering'){takeVehicle(a.v);state.mode='driving';hero.visible=false;toast('WASD DRIVE • F EXIT WHEN STOPPED')}else{state.mode='foot';state.x=a.from.x;state.z=a.from.z;hero.position.set(state.x,0,state.z);hero.visible=true;toast('ON FOOT • 1–3 LOADOUT • Q WEAPON WHEEL')}state.animation=null}}
 else if(state.mode==='foot'){let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),s=(keys.a||keys.arrowleft?1:0)-(keys.d||keys.arrowright?1:0),len=Math.hypot(f,s);const crouched=keys.c;const v=crouched?1.25:keys.shift?5.8:2.7;if(len){f/=len;s/=len}const dx=(Math.sin(yaw)*f+Math.cos(yaw)*s)*v*dt,dz=(Math.cos(yaw)*f-Math.sin(yaw)*s)*v*dt;const before={x:state.x,z:state.z};movePerson(state,dx,dz,personObstacles());state.speed=Math.hypot(state.x-before.x,state.z-before.z)/dt;if(state.weapon)state.yaw=yaw;else if(len)state.yaw+=Math.atan2(Math.sin(Math.atan2(dx,dz)-state.yaw),Math.cos(Math.atan2(dx,dz)-state.yaw))*Math.min(1,dt*12);if(keys[' ']&&!state.spaceDown&&state.jumpY===0)state.jumpVelocity=4.6;state.spaceDown=!!keys[' '];state.jumpVelocity-=9.8*dt;state.jumpY=Math.max(0,state.jumpY+state.jumpVelocity*dt);if(state.jumpY===0)state.jumpVelocity=0;hero.position.set(state.x,state.jumpY,state.z);hero.rotation.y=state.yaw;hero.visible=true;posePerson(hero,{speed:state.speed,dt,crouch:crouched?.7:state.jumpY>0?.3:0,weapon:state.weapon,recoil:state.recoil,reloading:inventory[state.weapon].reload>0})}else{hero.visible=false;state.speed=0}
 driver.visible=state.mode==='driving';if(driver.visible){const v=getVehicle();if(driver.parent!==v.mesh)v.mesh.add(driver);posePerson(driver,{dt,seated:true,reach:.9});driver.userData.arms[0].upper.rotation.z=(keys.a?.18:keys.d?-.18:0);driver.userData.arms[1].upper.rotation.z=(keys.a?.18:keys.d?-.18:0)}
 const nearVehicles=vehicles();for(const p of pedestrians){const dist=Math.hypot(p.x-state.x,p.z-state.z);p.mesh.visible=dist<145;if(dist>175)continue;p.panic=Math.max(0,p.panic-dt);p.stagger=Math.max(0,p.stagger-dt);p.wait=Math.max(0,p.wait-dt);let goal=p.path[p.target],dx=goal.x-p.x,dz=goal.z-p.z;if(Math.hypot(dx,dz)<.7){p.target=(p.target+1)%4;p.wait=1+Math.random()*2;goal=p.path[p.target];dx=goal.x-p.x;dz=goal.z-p.z}for(const v of nearVehicles){const d=Math.hypot(v.b.x-p.x,v.b.z-p.z);if(d<5&&Math.hypot(v.b.vx,v.b.vz)>3){p.panic=2;dx+=(p.x-v.b.x)*9;dz+=(p.z-v.b.z)*9}}const len=Math.max(.01,Math.hypot(dx,dz)),speed=p.stagger?0:p.panic?3.9:p.wait?0:p.speed;const before={x:p.x,z:p.z};movePerson(p,dx/len*speed*dt,dz/len*speed*dt,obstacles);if(Math.hypot(p.x-before.x,p.z-before.z)<.001&&speed>0)p.target=(p.target+1)%4;p.yaw=Math.atan2(dx,dz);p.mesh.position.set(p.x,0,p.z);p.mesh.rotation.y=p.yaw;posePerson(p.mesh,{speed,dt,crouch:p.stagger?.5:0});}
 }
 function updateHUD(){const foot=state.mode==='foot',slot=inventory[state.weapon];document.body.classList.toggle('on-foot',state.mode!=='driving');document.getElementById('weapon-name').textContent=WEAPONS[state.weapon].name;document.getElementById('ammo').textContent=slot.reload?'RELOADING':state.weapon?`${slot.ammo} / ${slot.reserve}`:'UNARMED';document.querySelectorAll('[data-weapon]').forEach(el=>{const selected=Number(el.dataset.weapon)===state.weapon;el.classList.toggle('selected',selected);el.setAttribute('aria-pressed',String(selected))});const v=foot?nearestVehicle(state,vehicles()):null;const text=state.animation?(state.mode==='entering'?'GETTING IN…':'GETTING OUT…'):state.mode==='driving'?'F • EXIT VEHICLE':v?'F • ENTER VEHICLE':'WASD MOVE · SHIFT RUN · DRAG MOUSE TO LOOK';document.getElementById('interact').textContent=text;document.getElementById('stance').textContent=state.mode==='driving'?'DRIVING':state.animation?'INTERACTING':'ON FOOT';}
 return {hero,state,pedestrians,inventory,step,interact,equip,reload,shoot,scare,updateHUD};
}
