import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]);const callbacks={};const nodes={};function node(){
 const context=new Proxy({createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get(t,k){return t[k]||(()=>{});}});
 return {style:{},hidden:false,dataset:{},children:[],classList:{toggle(){}},appendChild(n){this.children.push(n);},setAttribute(){},addEventListener(k,fn){this[k]=fn;},setPointerCapture(){},getContext(){return context;}};
}
for(const id of ids)nodes[id]=node();nodes['weapon-wheel'].hidden=true;const weaponButtons=Array.from({length:6},(_,i)=>Object.assign(node(),{dataset:{weapon:String(i%3)}}));const keyButtons=['w','a','s','d','shift'].map(k=>Object.assign(node(),{dataset:{key:k}}));globalThis.document={body:node(),createElement:node,getElementById:id=>{assert(nodes[id],`Missing DOM id: ${id}`);return nodes[id]},querySelectorAll:s=>s==='[data-weapon]'?weaponButtons:s==='[data-key]'?keyButtons:[]};globalThis.innerWidth=1280;globalThis.innerHeight=800;globalThis.devicePixelRatio=1;globalThis.addEventListener=(k,fn)=>callbacks[k]=fn;let frame;globalThis.requestAnimationFrame=fn=>frame=fn;
await import(new URL('../game.js',import.meta.url));let time=performance.now();function frames(n){for(let i=0;i<n;i++){time+=1000/60;frame(time)}}function key(k,down=true){callbacks[down?'keydown':'keyup']({key:k,repeat:false,preventDefault(){}})}
nodes.start.onclick();frames(3);assert.equal(nodes.stance.textContent,'ON FOOT');key('f');frames(110);key('f',false);assert.equal(nodes.stance.textContent,'DRIVING');key('w');frames(30);key('w',false);frames(100);key('r');key('r',false);key('f');key('f',false);frames(110);assert.equal(nodes.stance.textContent,'ON FOOT');key('2');key('2',false);frames(2);assert.equal(nodes['weapon-name'].textContent,'Pistol');testCanvas.pointerdown({pointerId:1,pointerType:'mouse',button:0,clientX:400,clientY:300});testCanvas.pointerup();frames(2);assert.equal(nodes.ammo.textContent,'11 / 72');key('r');key('r',false);frames(100);assert.equal(nodes.ammo.textContent,'12 / 71');key('q');key('q',false);assert.equal(nodes['weapon-wheel'].hidden,false);weaponButtons[2].onclick();assert.equal(nodes['weapon-wheel'].hidden,true);frames(1);assert.equal(nodes['weapon-name'].textContent,'SMG');key('p');key('p',false);assert.equal(nodes.overlay.style.display,'flex');
console.log('Gameplay integration passed: startup, on foot, enter, drive, repair, exit, equip, shoot, reload, weapon wheel, pause; all scene transforms finite. Renderer stubbed: no visual/WebGL verification.');
